# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 15-jdk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build -S
